### PR TITLE
Quick fix for issue-95. Command buffer output not being cleared.

### PR DESCRIPTION
**Pull request by wilsonk**
Seems to work. Hopefully it is correct. Not sure if this fixes all cases, as I just started using lilly :)

### CODE REVIEW

**Review by tauraamui — CHANGES_REQUESTED** [review]
Hey! I only just noticed these PRs, I'm so sorry! I will go through them all one by one. Could you add a small unit test for this if possible?

**Comment by tauraamui** [comment]
I've waited about a month since that's how long it took me to notice these PRs in the first place. In about a week's time I'm intending to implement the tests on these PRs for you and then merge them, unless you:
- remove the PR entirely (hopefully not, but up to you)
- inform me you would like to do this work

**Comment by wilsonk** [comment]
I added a test for this, but have no idea if it is correct or sufficient. Hopefully it is ok.

**Review by tauraamui — APPROVED** [review]
This is great, thank you!

lgtm-gif

**Comment by tauraamui** [comment]
I seem to have signed commits turned on as a requirement for master branch protection, let me disable that for your convenience.

**Pull request merged**
