### PR TITLE
Add the zz action for centering text vertially

### PR DESCRIPTION
**Pull request by wilsonk**
This seems to work the same as in Vim. I use it regularly there, so I thought I would add it to lilly also :)

That seems to be the way I am looking at these PR's...if I use the actions in Vim/NVim fairly often, then I try it with lilly. If it isn't implemented yet then I take a crack at it. Please let me know if you would prefer that I don't continue with this method, or if there is something more pressing that you would prefer I look at ;)

### CODE REVIEW

**Review by tauraamui — CHANGES_REQUESTED** [review]
I'm happy to accept these changes as is for now, but please add some tests. Long term however this should be handled as part of the chord flow/system.

**Comment by tauraamui** [comment]
I've waited about a month since that's how long it took me to notice these PRs in the first place. In about a week's time I'm intending to implement the tests on these PRs for you and then merge them, unless you:
- remove the PR entirely (hopefully not, but up to you)
- inform me you would like to do this work

**Comment by wilsonk** [comment]
Added tests.

**Comment by tauraamui** [comment]
I intend to manually test this change as I have no idea what you're on about or how it works I've apparently never used this feature from VIM/Neovim before. Please bear with me whilst I get around to doing so.

**Comment by tauraamui** [comment]
This PR has made me facepalm at myself for moving count fields from view into the leader state struct incorrectly.

**Review by tauraamui — APPROVED** [review]
tiger-yay

**Pull request merged**
