### PR TITLE
Add syntax highlighting for more languages

### PR DESCRIPTION
**Pull request by Kaamkiya**
Added JavaScript, TypeScript, Python, and Perl.

Hope it helps, at least a little :)

### CODE REVIEW

**Comment by tauraamui** [comment]
Thanks! Please merge the latest main to (hopefully) fix the failing CI run. I apparently cannot do it for you.

**Comment by Kaamkiya** [comment]
Should be fixed now. I updated the tests to match the new syntaxes that I added, because it was asserting `wrkspace.syntaxes.len == 4` when I've added 4 more, so it should assert for 8.

Small things like that get me every time...

Anyway, should be good to merge now.

**Review by tauraamui — APPROVED** [review]
dolphin-love

**Comment by tauraamui** [comment]
> Should be fixed now. I updated the tests to match the new syntaxes that I added, because it was asserting `wrkspace.syntaxes.len == 4` when I've added 4 more, so it should assert for 8.
> 
> Small things like that get me every time...
> 
> Anyway, should be good to merge now.

Yeah I missed why the tests were failing to, I need to resolve those compiler warns, it was helping hide the real fails and I couldn't really read what was going on on my phone at the time.

**Pull request merged**
