### PR TITLE
Add a few more actions

### PR DESCRIPTION
**Pull request by wilsonk**
Adding a few more simple actions like 'L,H,M,gg and G' key movements. Adds 'f' searching in one line of text. Also, adds 'R' for continuous replacing of text, but this only works on the current line up to the last character.

### CODE REVIEW

**Review by tauraamui — CHANGES_REQUESTED** [review]
These changes are awesome, please add some tests. Again, if you need help re: implementing tests then please let me know.

**Comment by tauraamui** [comment]
I've waited about a month since that's how long it took me to notice these PRs in the first place. In about a week's time I'm intending to implement the tests on these PRs for you and then merge them, unless you:
- remove the PR entirely (hopefully not, but up to you)
- inform me you would like to do this work

**Comment by wilsonk** [comment]
Oh, hello Adam, sorry for the late reply. I did see this a couple weeks ago, but have a large contract on the go here, so I couldn't get to the tests and then forgot about these PR's. By all means, go ahead and write tests and submit under your account (if that is a concern...I am not concerned about attribution for these very small contributions of mine :)  ), or just submit however you like.

I will check how you write the tests, and then endeavor to do the same if I find time in September, after the contract is finished, to come back to work on Lilly a little bit.

Great project. Hope all goes well, moving forward.

**Comment by tauraamui** [comment]
> Oh, hello Adam, sorry for the late reply. I did see this a couple weeks ago, but have a large contract on the go here, so I couldn't get to the tests and then forgot about these PR's. By all means, go ahead and write tests and submit under your account (if that is a concern...I am not concerned about attribution for these very small contributions of mine :) ), or just submit however you like.
> 
> I will check how you write the tests, and then endeavor to do the same if I find time in September, after the contract is finished, to come back to work on Lilly a little bit.
> 
> Great project. Hope all goes well, moving forward.

I am very appreciative of your time and contribution so I would like to attribute you as best as I can here in the normal fashion. As such I will (hopefully soon) attempt to clone your fork and update these branches on which these PRs are based, since Github assures me I have the necessary upstream rights to do so. If you have any questions re: the changes feel free to join the Discord and ask them there :) . I hope your contract is going/goes well, good luck!
Screenshot 2024-07-27 23 28 46

**Comment by wilsonk** [comment]
Added tests and cleaned up a bit.

**Comment by wilsonk** [comment]
Sorry, forgot to add a couple tests for L,H,M and I had non-descriptive names for the other tests previously. My bad.

**Comment by wilsonk** [comment]
Didn't notice 'r' command was implemented by Valentine. Lots of good tests. So I changed this test to the 'R' command, but it doesn't perform like Vim by overwriting the line in place, right now is just keeps overwriting the character it is on, until 'escape' is pressed. Still useful, IMHO, but not exactly  the same as Vim yet.

**Comment by tauraamui** [comment]
Don't worry about fixing the above failing CI run, I'll sort it out and update the branch the PR is referring to via a clone of your fork as I have permissions to do so.

**Pull request closed without merging**
